In [9]:
import numpy as np

a = np.array([1,2,3])
print(a)

c = a//2
print(c)

[1 2 3]
[0 1 1]


In [34]:
a = np.linspace(0,1,5)
a

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [64]:
a = np.array([1,2,3,4])
a = np.append(a,5)
np.insert(a,1,1)

array([1, 1, 2, 3, 4, 5])

In [67]:
a = np.empty(4)
a

array([4.9e-324, 9.9e-324, 1.5e-323, 2.0e-323])

In [70]:
b = np.full(3,7.)
b

array([7., 7., 7.])

In [101]:
np.random.seed(0)
c = np.random.randint(0,8,8)
print(c)
b = list(c)
b.index(5)

[4 7 5 0 3 3 3 7]


2

In [94]:
a = np.random.default_rng()
a.random(3)

array([0.12985657, 0.99668998, 0.7586843 ])

In [102]:
np.where(c==8)[0][0]
next(i[0] for i,v in np.ndenumerate(c) if(v==8)
     np.searchsorted(c,8)

SyntaxError: invalid syntax (3583372446.py, line 3)